subjects = {
  "STEM": [
    "EarthAndLifeScience",
    "PhysicalScience",
    "EarthScience",
    "GenBio1",
    "GenBio2",
    "GenPhysics1",
    "GenPhysics2",
    "GenChem1",
    "GenChem2",
    "GeneralMath",
    "StatisticsAndProbability",
    "PreCalculus",
    "BasicCalculus",

    "OralCommunication",
    "Reading_and_Writing",
    "MediaandInformationLiteracy",
    "t21stCenturyLiteratureFromThePhilippinesAndTheWorld",
    "ContemporaryPhilippineArtsFromTheRegions",

    "PagbasaAtPagsusuriNgIbatIbangTekstoTungoSaPananaliksik",
    "KomunikasyonAtPananaliksikSaWikaAtKulturangPilipino",
    "PersonalDevelopment",
    "IntroductionToThePhilosophyOfTheHumanPerson",
    "UnderstandingCultureSocietyAndPolitics",
    "DisasterReadinessAndRisk_Reduction",
    "PhysicalEducationAndHealth",
    "PhysicalEducationAndHealth2",
    "PhysicalEducationandHealth3",
    "PhysicalEducationAndHealth4",
  ],
  "ABM": [
    "EarthAndLifeScience",
    "PhysicalScience",
    "EarthScience",

    "GeneralMath",
    "StatisticsAndProbability",
    "BusinessMath",
    "BusinessFinance",

    "OralCommunication",
    "Reading_and_Writing",
    "MediaandInformationLiteracy",
    "t21stCenturyLiteratureFromThePhilippinesAndTheWorld",
    "ContemporaryPhilippineArtsFromTheRegions",

    "PagbasaAtPagsusuriNgIbatIbangTekstoTungoSaPananaliksik",
    "KomunikasyonAtPananaliksikSaWikaAtKulturangPilipino",
    "PersonalDevelopment",
    "IntroductionToThePhilosophyOfTheHumanPerson",
    "UnderstandingCultureSocietyAndPolitics",
    "DisasterReadinessAndRisk_Reduction",
    "PhysicalEducationAndHealth",
    "PhysicalEducationAndHealth2",
    "PhysicalEducationandHealth3",
    "PhysicalEducationAndHealth4",
    "OrganizationAndManagement",
    "PrinciplesOfMarketing",
    "BusinessMarketing",
    "BusinessEnterpriseAndSimulation",
    "F1_FundamentalsOfAccountancyBusinessAndManagement1",
    "F2_FundamentalsofAccountancyBusinessAndManagement2",
    "AppliedEconomicsBusiness",
    "EthicsAndSocial_Responsibility",
  ],
  "HUMSS": [
    "EarthAndLifeScience",
    "PhysicalScience",
    "EarthScience",

    "GeneralMath",
    "StatisticsAndProbability",
    "OralCommunication",
    "Reading_and_Writing",
    "MediaandInformationLiteracy",
    "t21stCenturyLiteratureFromThePhilippinesAndTheWorld",
    "ContemporaryPhilippineArtsFromTheRegions",
    "CreativeNonfiction",

    "PagbasaAtPagsusuriNgIbatIbangTekstoTungoSaPananaliksik",
    "KomunikasyonAtPananaliksikSaWikaAtKulturangPilipino",

    "CreativeWriting_Malikhaing_Pagsulat",

    "PersonalDevelopment",
    "IntroductionToThePhilosophyOfTheHumanPerson",
    "UnderstandingCultureSocietyAndPolitics",
    "DisasterReadinessAndRisk_Reduction",
    "PhysicalEducationAndHealth",
    "PhysicalEducationAndHealth2",
    "PhysicalEducationandHealth3",
    "PhysicalEducationAndHealth4",
    "IntroductionToWorldReligionsAndBeliefSystems",
    "Community_EngagementSolidarityAndCitizenship",
    "PhilippinePoliticsandGovernance",
    "DisciplinesAndIdeasInTheSocialSciences",
  ],
  "GAS": [
    "EarthAndLifeScience",
    "PhysicalScience",
    "EarthScience",

    "GeneralMath",
    "StatisticsAndProbability",

    "OralCommunication",
    "Reading_and_Writing",
    "MediaandInformationLiteracy",
    "t21stCenturyLiteratureFromThePhilippinesAndTheWorld",
    "ContemporaryPhilippineArtsFromTheRegions",
    "CreativeWriting",

    "PagbasaAtPagsusuriNgIbatIbangTekstoTungoSaPananaliksik",
    "KomunikasyonAtPananaliksikSaWikaAtKulturangPilipino",

    "PersonalDevelopment",
    "IntroductionToThePhilosophyOfTheHumanPerson",
    "UnderstandingCultureSocietyAndPolitics",
    "DisasterReadinessAndRisk_Reduction",
    "PhysicalEducationAndHealth",
    "PhysicalEducationAndHealth2",
    "PhysicalEducationandHealth3",
    "PhysicalEducationAndHealth4",
    "Humanities1_Politics",
    "Humanities2_intro",
    "SocialScience1",
    "OrganizationAndManagement2",
    "AppliedEconomics2",
    "IntroToWorldReligionsAndSytemBeliefs",
    "PhilippinePiliticsAndGovernance",
  ],
  "TVL": [
    "EarthAndLifeScience",
    "PhysicalScience",
    "EarthScience",

    "GeneralMath",
    "StatisticsAndProbability",

    "OralCommunication",
    "Reading_and_Writing",
    "MediaandInformationLiteracy",
    "t21stCenturyLiteratureFromThePhilippinesAndTheWorld",
    "ContemporaryPhilippineArtsFromTheRegions",
    "CreativeWriting",

    "PagbasaAtPagsusuriNgIbatIbangTekstoTungoSaPananaliksik",
    "KomunikasyonAtPananaliksikSaWikaAtKulturangPilipino",

    "PersonalDevelopment",
    "IntroductionToThePhilosophyOfTheHumanPerson",
    "UnderstandingCultureSocietyAndPolitics",
    "DisasterReadinessAndRisk_Reduction",
    "PhysicalEducationAndHealth",
    "PhysicalEducationAndHealth2",
    "PhysicalEducationandHealth3",
    "PhysicalEducationAndHealth4",
    "SafetyAndFirstAid",
    "HumanMovement",
    "FundamentalsOfCoaching",
  ],
}
